import express from 'express';
import { createServer } from 'http';
import { WebSocket, WebSocketServer } from 'ws';
import path from 'path';
import { GoogleGenAI, Type } from '@google/genai';
import dotenv from 'dotenv';
import { createServer as createViteServer } from 'vite';
import { PREBAKED_QUIZZES } from './src/data/prebakedQuizzes';
import { GameSession, Player, Question, Quiz, WSMessage, GameState } from './src/types';

dotenv.config();

const app = express();
const server = createServer(app);
const wss = new WebSocketServer({ server });
const PORT = 3000;

// Initialize Gemini API
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

app.use(express.json());

// Server-side database of quizzes in-memory (seeded with pre-baked quizzes)
const quizzes: Quiz[] = [...PREBAKED_QUIZZES];

// In-memory sessions
interface SessionWithSockets extends GameSession {
  hostId: string;
  hostSocket: WebSocket | null;
  playerSockets: { [playerId: string]: WebSocket };
  botTimers: NodeJS.Timeout[];
  timerInterval: NodeJS.Timeout | null;
  hostDisconnectTimeout?: NodeJS.Timeout | null;
}

const activeSessions: { [pin: string]: SessionWithSockets } = {};

// Helper: Generate pin
function generatePin(): string {
  let pin = '';
  do {
    pin = Math.floor(100000 + Math.random() * 900000).toString();
  } while (activeSessions[pin]);
  return pin;
}

// REST API Endpoints
app.get('/api/quizzes', (req, res) => {
  res.json(quizzes);
});

app.post('/api/generate-quiz', async (req, res) => {
  const { topic, difficulty = 'Medium', ageGroup = '10-15 years' } = req.body;
  if (!topic) {
    return res.status(400).json({ error: 'Topic is required' });
  }

  try {
    const prompt = `Create a fun, educational classroom multiple-choice quiz about "${topic}".
Difficulty level should be oriented for "${difficulty}" difficulty, perfect for the age group of "${ageGroup}".
The response must have exactly 5 questions.
Each question should be engaging and have exactly 4 diverse options. Save the correct answer index (0 to 3) representing the index in the options list.
Assign a reasonable time limit in seconds (10 to 30) depending on question complexity.`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.5-flash',
      contents: prompt,
      config: {
        systemInstruction: `You are an expert curriculum developer and quiz designer who creates high-energy Kahoot-style classroom games.
You always respond with valid JSON that adheres strictly to the requested schema. Make the options playful and correct answer completely indisputable.`,
        responseMimeType: 'application/json',
        responseSchema: {
          type: Type.OBJECT,
          required: ['title', 'description', 'category', 'questions'],
          properties: {
            title: {
              type: Type.STRING,
              description: 'An exciting, catchy title for the quiz (e.g., "The Solar System Mystery tour" or "Math Wonders")',
            },
            description: {
              type: Type.STRING,
              description: 'A brief 1-sentence synopsis explaining what players will learn.',
            },
            category: {
              type: Type.STRING,
              description: 'A category tag matching the topic (e.g., Science, Math, History, Pop Culture)',
            },
            questions: {
              type: Type.ARRAY,
              description: 'Array of exactly 5 multiple choice questions.',
              items: {
                type: Type.OBJECT,
                required: ['text', 'options', 'correctOptionIndex', 'timeLimit'],
                properties: {
                  text: {
                    type: Type.STRING,
                    description: 'The quiz question. Keep it concise enough to read on screen quickly.',
                  },
                  options: {
                    type: Type.ARRAY,
                    description: 'Exactly 4 distinct answers.',
                    items: { type: Type.STRING },
                  },
                  correctOptionIndex: {
                    type: Type.INTEGER,
                    description: 'The zero-based index of the correct option (0, 1, 2, or 3).',
                  },
                  timeLimit: {
                    type: Type.INTEGER,
                    description: 'Time limit to answer in seconds (typically 15 or 20).',
                  },
                },
              },
            },
          },
        },
      },
    });

    const parsedData = JSON.parse(response.text || '{}');
    if (!parsedData.title || !parsedData.questions || parsedData.questions.length === 0) {
      throw new Error('Incomplete JSON response generated by AI');
    }

    // Assign IDs to questions
    const generatedQuiz: Quiz = {
      id: `quiz-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      title: parsedData.title,
      description: parsedData.description || `An AI-generated quiz about ${topic}`,
      category: parsedData.category || 'General',
      questions: parsedData.questions.map((q: any, idx: number) => ({
        id: `q-${idx}-${Date.now()}`,
        text: q.text,
        options: q.options.slice(0, 4),
        correctOptionIndex: Number(q.correctOptionIndex) ?? 0,
        timeLimit: Number(q.timeLimit) || 15,
      })),
      createdAt: new Date().toISOString(),
    };

    quizzes.push(generatedQuiz);
    res.json(generatedQuiz);
  } catch (err: any) {
    console.error('Quiz Generation Error: ', err);
    res.status(500).json({ error: err.message || 'Failed to generate quiz' });
  }
});

// Helper: Broadcast to all players + host in a session
function broadcastSessionState(pin: string) {
  const session = activeSessions[pin];
  if (!session) return;

  const publicState: GameSession = {
    pin: session.pin,
    quizId: session.quizId,
    quizTitle: session.quizTitle,
    questions: session.questions,
    currentQuestionIndex: session.currentQuestionIndex,
    state: session.state,
    timer: session.timer,
    players: session.players,
    answersCount: session.answersCount,
    totalQuestions: session.totalQuestions,
    questionStartTime: session.questionStartTime,
    hasBots: session.hasBots,
  };

  const message: WSMessage = {
    type: 'server:game_state',
    payload: publicState,
  };

  const messageStr = JSON.stringify(message);

  // Send to Host
  if (session.hostSocket && session.hostSocket.readyState === WebSocket.OPEN) {
    session.hostSocket.send(messageStr);
  }

  // Send to All Players
  Object.values(session.playerSockets).forEach((socket) => {
    if (socket.readyState === WebSocket.OPEN) {
      socket.send(messageStr);
    }
  });
}

// Bot Generator Helper Names
const BOT_PROFILES = [
  { nickname: 'Smart Fox 🦊', avatar: '🦊' },
  { nickname: 'Speedy Dino 🦖', avatar: '🦖' },
  { nickname: 'Cosmic Panda 🐼', avatar: '🐼' },
  { nickname: 'Tech Koala 🐨', avatar: '🐨' },
  { nickname: 'Neon Tiger 🐯', avatar: '🐯' },
];

function toggleBots(pin: string, enable: boolean) {
  const session = activeSessions[pin];
  if (!session) return;

  session.hasBots = enable;

  if (enable) {
    // Add bots that don't already exist
    BOT_PROFILES.forEach((profile, idx) => {
      const botId = `bot-${idx}`;
      if (!session.players[botId]) {
        session.players[botId] = {
          id: botId,
          nickname: profile.nickname,
          avatar: profile.avatar,
          score: 0,
          streak: 0,
          lastAnswerCorrect: null,
          lastPointsEarned: 0,
          answeredThisQuestion: false,
          isBot: true,
        };
      }
    });
  } else {
    // Remove all bots
    Object.keys(session.players).forEach((pId) => {
      if (pId.startsWith('bot-')) {
        delete session.players[pId];
      }
    });
  }

  broadcastSessionState(pin);
}

// Handle Bot Answers when Question is Live
function scheduleBotAnswers(pin: string) {
  const session = activeSessions[pin];
  if (!session || !session.hasBots) return;

  // Clear existing timers
  session.botTimers.forEach(clearTimeout);
  session.botTimers = [];

  const currentQuestion = session.questions[session.currentQuestionIndex];
  if (!currentQuestion) return;

  Object.values(session.players).forEach((player) => {
    if (player.isBot) {
      // Mark bot as not answered
      player.answeredThisQuestion = false;

      // Random delay to simulate real answer speeds
      const delay = Math.random() * (currentQuestion.timeLimit - 2) * 1000 + 1000;

      const timer = setTimeout(() => {
        submitBotAnswer(pin, player.id, currentQuestion);
      }, delay);

      session.botTimers.push(timer);
    }
  });
}

function submitBotAnswer(pin: string, botId: string, question: Question) {
  const session = activeSessions[pin];
  if (!session || session.state !== 'question') return;

  const bot = session.players[botId];
  if (!bot || bot.answeredThisQuestion) return;

  // Brain: 70% chance correct, 30% chance wrong option
  const isCorrect = Math.random() < 0.7;
  let chosenIndex = question.correctOptionIndex;
  
  if (!isCorrect) {
    const wrongIndices = [0, 1, 2, 3].filter(idx => idx !== question.correctOptionIndex);
    chosenIndex = wrongIndices[Math.floor(Math.random() * wrongIndices.length)];
  }

  // Submit Answer Action
  processAnswer(pin, botId, chosenIndex);
}

// Central processing for answers
function processAnswer(pin: string, playerId: string, chosenOptionIndex: number) {
  const session = activeSessions[pin];
  if (!session || session.state !== 'question') return;

  const player = session.players[playerId];
  if (!player || player.answeredThisQuestion) return;

  player.answeredThisQuestion = true;
  const currentQuestion = session.questions[session.currentQuestionIndex];
  const isCorrect = chosenOptionIndex === currentQuestion.correctOptionIndex;

  let pointsEarned = 0;
  if (isCorrect) {
    const timeTaken = (Date.now() - session.questionStartTime) / 1000;
    const timeRatio = Math.max(0, Math.min(1, timeTaken / currentQuestion.timeLimit));
    
    // Kahoot points calculation: Max 1000, Min 500 based on answer speed
    const speedPoints = Math.round(1000 - (500 * timeRatio));
    
    // Streak multiplier points
    player.streak += 1;
    const streakBonus = Math.min(5, player.streak) * 50; // up to 250 points bonus
    pointsEarned = speedPoints + streakBonus;

    player.score += pointsEarned;
    player.lastAnswerCorrect = true;
    player.lastPointsEarned = pointsEarned;
  } else {
    player.streak = 0;
    player.lastAnswerCorrect = false;
    player.lastPointsEarned = 0;
  }

  // Send direct feedback back to the student socket if correct
  if (!player.isBot) {
    const pSocket = session.playerSockets[playerId];
    if (pSocket && pSocket.readyState === WebSocket.OPEN) {
      pSocket.send(JSON.stringify({
        type: 'server:player_feedback',
        payload: {
          isCorrect,
          pointsEarned,
          currentStreak: player.streak,
          totalScore: player.score,
        }
      }));
    }
  }

  // Increment total answer ticks
  const activePlayers = Object.values(session.players);
  const activeHumanSockets = Object.keys(session.playerSockets).length;
  // Account for bot / human count
  const totalAnsweringPlayers = activePlayers.length;
  
  const answeredCount = activePlayers.filter(p => p.answeredThisQuestion).length;
  session.answersCount = answeredCount;

  // If everyone answered, auto-reveal!
  if (answeredCount >= totalAnsweringPlayers && totalAnsweringPlayers > 0) {
    revealAnswers(pin);
  } else {
    broadcastSessionState(pin);
  }
}

function revealAnswers(pin: string) {
  const session = activeSessions[pin];
  if (!session) return;

  // Clear timers/intervals
  if (session.timerInterval) clearInterval(session.timerInterval);
  session.botTimers.forEach(clearTimeout);
  session.botTimers = [];

  session.state = 'reveal';
  broadcastSessionState(pin);
}

// Setup WebSocket Connections
wss.on('connection', (ws) => {
  let boundPin: string | null = null;
  let boundPlayerId: string | null = null;
  let isHost = false;

  ws.on('message', (messageBuffer) => {
    try {
      const message: WSMessage = JSON.parse(messageBuffer.toString());
      const { type, payload } = message;

      switch (type) {
        case 'host:create': {
          const { quizId } = payload;
          const quiz = quizzes.find((q) => q.id === quizId);
          if (!quiz) {
            ws.send(JSON.stringify({ type: 'server:error', payload: 'Quiz not found' }));
            return;
          }

          const pin = generatePin();
          isHost = true;
          boundPin = pin;

          activeSessions[pin] = {
            pin,
            quizId: quiz.id,
            quizTitle: quiz.title,
            questions: quiz.questions,
            currentQuestionIndex: 0,
            state: 'lobby',
            timer: 0,
            players: {},
            answersCount: 0,
            totalQuestions: quiz.questions.length,
            questionStartTime: 0,
            hasBots: false,
            hostId: `host-${pin}`,
            hostSocket: ws,
            playerSockets: {},
            botTimers: [],
            timerInterval: null,
          };

          broadcastSessionState(pin);
          break;
        }

        case 'ping': {
          ws.send(JSON.stringify({ type: 'server:pong' }));
          break;
        }

        case 'host:reconnect': {
          const { pin } = payload;
          const parsedPin = String(pin).trim();
          const session = activeSessions[parsedPin];
          if (!session) {
            ws.send(JSON.stringify({ type: 'server:error', payload: 'Reconnection failed: room no longer active.' }));
            return;
          }

          if (session.hostDisconnectTimeout) {
            clearTimeout(session.hostDisconnectTimeout);
            session.hostDisconnectTimeout = null;
          }

          isHost = true;
          boundPin = parsedPin;
          session.hostSocket = ws;

          broadcastSessionState(parsedPin);
          break;
        }

        case 'player:reconnect': {
          const { pin, playerId, nickname, avatar } = payload;
          const parsedPin = String(pin).trim();
          const session = activeSessions[parsedPin];
          if (!session) {
            ws.send(JSON.stringify({ type: 'server:error', payload: 'Reconnection failed: Room ended.' }));
            return;
          }

          boundPin = parsedPin;
          boundPlayerId = playerId;
          isHost = false;

          if (!session.players[playerId]) {
            session.players[playerId] = {
              id: playerId,
              nickname: nickname || `Player ${Object.keys(session.players).length + 1}`,
              avatar: avatar || '🦊',
              score: 0,
              streak: 0,
              lastAnswerCorrect: null,
              lastPointsEarned: 0,
              answeredThisQuestion: false,
              isBot: false,
            };
          }

          session.playerSockets[playerId] = ws;

          ws.send(JSON.stringify({
            type: 'server:player_feedback',
            payload: { reconnected: true, player: session.players[playerId], pin: parsedPin }
          }));

          broadcastSessionState(parsedPin);
          break;
        }

        case 'player:join': {
          const { pin, nickname, avatar } = payload;
          const parsedPin = String(pin).trim();
          const session = activeSessions[parsedPin];

          if (!session) {
            ws.send(JSON.stringify({ type: 'server:error', payload: 'Room not found! Ensure PIN is correct.' }));
            return;
          }

          if (session.state !== 'lobby') {
            ws.send(JSON.stringify({ type: 'server:error', payload: 'Game has already started!' }));
            return;
          }

          // Generate or assign playerId
          const playerId = `p-${Date.now()}-${Math.floor(Math.random() * 1000)}`;
          boundPin = parsedPin;
          boundPlayerId = playerId;

          const newPlayer: Player = {
            id: playerId,
            nickname: nickname || `Player ${Object.keys(session.players).length + 1}`,
            avatar: avatar || '🦊',
            score: 0,
            streak: 0,
            lastAnswerCorrect: null,
            lastPointsEarned: 0,
            answeredThisQuestion: false,
            isBot: false,
          };

          session.players[playerId] = newPlayer;
          session.playerSockets[playerId] = ws;

          // Confirm successful join to player
          ws.send(JSON.stringify({
            type: 'server:player_feedback',
            payload: { joined: true, player: newPlayer, pin: parsedPin }
          }));

          broadcastSessionState(parsedPin);
          break;
        }

        case 'host:toggle_bots': {
          if (!isHost || !boundPin) return;
          const { enable } = payload;
          toggleBots(boundPin, enable);
          break;
        }

        case 'host:start_game': {
          if (!isHost || !boundPin) return;
          const session = activeSessions[boundPin];
          if (!session) return;

          // Transition to Get Ready countdown
          session.state = 'get_ready';
          session.currentQuestionIndex = 0;
          session.answersCount = 0;
          broadcastSessionState(boundPin);

          // After 3 seconds, trigger the first question
          setTimeout(() => {
            startQuestion(boundPin!);
          }, 4000);
          break;
        }

        case 'host:reveal_answer': {
          if (!isHost || !boundPin) return;
          revealAnswers(boundPin);
          break;
        }

        case 'host:show_scoreboard': {
          if (!isHost || !boundPin) return;
          const session = activeSessions[boundPin];
          if (session) {
            session.state = 'scoreboard';
            broadcastSessionState(boundPin);
          }
          break;
        }

        case 'host:next_question': {
          if (!isHost || !boundPin) return;
          const session = activeSessions[boundPin];
          if (!session) return;

          if (session.currentQuestionIndex + 1 >= session.totalQuestions) {
            session.state = 'podium';
            broadcastSessionState(boundPin);
          } else {
            session.currentQuestionIndex += 1;
            session.answersCount = 0;
            // Clear status and trigger ready
            Object.values(session.players).forEach((p) => {
              p.answeredThisQuestion = false;
              p.lastAnswerCorrect = null;
              p.lastPointsEarned = 0;
            });

            session.state = 'get_ready';
            broadcastSessionState(boundPin);

            setTimeout(() => {
              startQuestion(boundPin!);
            }, 3000);
          }
          break;
        }

        case 'player:submit_answer': {
          if (!boundPin || !boundPlayerId) return;
          const { optionIndex } = payload;
          processAnswer(boundPin, boundPlayerId, optionIndex);
          break;
        }

        default:
          break;
      }
    } catch (e) {
      console.error('WS Error:', e);
    }
  });

  // Handle disconnects elegantly
  ws.on('close', () => {
    if (isHost && boundPin) {
      const session = activeSessions[boundPin];
      if (session) {
        session.hostSocket = null;
        console.log(`Host socket disconnected for PIN ${boundPin}. Waiting 45s grace period for reconnection...`);
        
        // Clear any old hostDisconnectTimeout
        if (session.hostDisconnectTimeout) clearTimeout(session.hostDisconnectTimeout);
        
        session.hostDisconnectTimeout = setTimeout(() => {
          // If 45 seconds have passed and they still didn't reconnect, purge session!
          const activeSession = activeSessions[boundPin!];
          if (activeSession && !activeSession.hostSocket) {
            console.log(`Grace period expired for PIN ${boundPin!}. Purging session.`);
            if (activeSession.timerInterval) clearInterval(activeSession.timerInterval);
            activeSession.botTimers.forEach(clearTimeout);

            Object.values(activeSession.playerSockets).forEach((pSocket) => {
              if (pSocket.readyState === WebSocket.OPEN) {
                pSocket.send(JSON.stringify({ type: 'server:error', payload: 'Host disconnected! Session ended.' }));
              }
            });
            delete activeSessions[boundPin!];
          }
        }, 45000); // 45 seconds grace period
      }
    } else if (boundPin && boundPlayerId) {
      // Player disconnected logic - keep in roster for reconnection
      const session = activeSessions[boundPin];
      if (session) {
        delete session.playerSockets[boundPlayerId];
        console.log(`Player socket disconnected ${boundPlayerId} (PIN ${boundPin}). Keeping they in roster.`);
        broadcastSessionState(boundPin);
      }
    }
  });
});

function startQuestion(pin: string) {
  const session = activeSessions[pin];
  if (!session) return;

  const question = session.questions[session.currentQuestionIndex];
  if (!question) return;

  session.state = 'question';
  session.timer = question.timeLimit;
  session.questionStartTime = Date.now();
  session.answersCount = 0;

  // Clear any existing active bot timers and reschedule
  session.botTimers.forEach(clearTimeout);
  session.botTimers = [];

  // Reset answer states
  Object.values(session.players).forEach((p) => {
    p.answeredThisQuestion = false;
  });

  broadcastSessionState(pin);

  // Trigger bots to think
  scheduleBotAnswers(pin);

  // Interval timer ticks
  if (session.timerInterval) clearInterval(session.timerInterval);
  
  session.timerInterval = setInterval(() => {
    session.timer -= 1;
    if (session.timer <= 0) {
      revealAnswers(pin);
    } else {
      broadcastSessionState(pin);
    }
  }, 1000);
}

// Attach Vite middleware in development
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  // Bind server to port 3000 and interface 0.0.0.0
  server.listen(PORT, '0.0.0.0', () => {
    console.log(`Server is running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
